CUDA_VISIBLE_DEVICES=2 python3 ./trans_anchor_map_cls.py \
    --cuda \
    --batch_size 256 \
    --nepoch 1000 \
    --data_root '/data' \
    --dataset 'AWA2' \
    --image_embedding 'res101' \
    --class_embedding 'att' \
    --resSize 2048 \
    --attSize 85 \
    --preprocessing \
    --lr 0.0001 \
    --ap_lambda 10 \
    --manualSeed 342 \
    --epoch_da 100 \
    --epoch_cls 20 \
    --nz 85 \
    --log_path 'dasunseen.xls' \
    --version 'AD3C' 